---
- name: initial setup of the priorities tool
  hosts: dev 
  connection: ssh
  remote_user: "{{ remote_user }}"
  sudo: no

  vars:
    app_name: cogs-priorities
    venv_path: '/usr/local/venv/cogs-priorities'
    project_path: '/usr/local/apps/cogs-priorities'
    dbname: 'cogs'
    webuser: www-data
    debug: 'True'
    domain: 'localhost'
    manage: "{{ venv_path }}/bin/python {{ project_path }}/priorities/manage.py"

  tasks:

    - name: install flatblocks (unsafe???)
      command: "{{ manage }} loaddata {{ project_path }}/priorities/fixtures/flatblocks.json"

    - name: install base layers (unsafe???)
      command: "{{ manage }} loaddata {{ project_path }}/priorities/fixtures/project_base_layers.json"

    # COPY data

    # Update git (if vagrant)

    # Trigger restart handlers if git was updated or we're on vagrantbox

    # handler to install data
    # INSTALL data
    # vars['data_dir']  = posixpath.join(vars['app_dir'], '..', 'testdata')
    # run('cd %(app_dir)s && %(venv)s/bin/python manage.py \
    #         import_planning_units \
    #         %(data_dir)s/planning_units.shp \
    #         %(data_dir)s/metrics.xls \
    #         %(data_dir)s/planning_units.shp' % vars)

    # handler to restart services (common include to provision.yml)
